### ISSUE TITLE
[REPO] Add automated tests to pull requests

### ISSUE THREAD

**Issue by JoshQuake** [JoshQuake/BlenderTools#16]
Need to implement automated testing to pull requests. Currently just does python CodeQL.

**Comment by jack-yao91** [comment]
Hi @JoshQuake, thanks again for heading up this project. I got the automated tests running in my fork
https://github.com/poly-hammer/BlenderTools/tree/main/.github/workflows

I had to make some tweaks to the `run_test.py` script, and the docker images were too large not to have pre-cached on the runner, so we utilized a self hosted runner from our github org's runner pool. We had to meet the min specs for Unreal and also had to make a blender 4.1 image since it looks like [this repo](https://github.com/nytimes/rd-blender-docker) is not putting out new blender docker images anymore.

Anyways, I wanted to post this here so you at least have the updated code and workflows. If you have VMs to create self hosted runners on hopefully this helps. Another option is, we could make you a admin of our fork and let you continue on owning the project from there. 

Like I mentioned earlier, we have a invested interest in making sure this project stays around and up to date and compatible with what we are building. So if we can get synced up we would be willing to help contribute.

**Comment by JoshQuake** [comment]
Hey @jack-yao91 thanks for reaching out! I'd love to join up! Like you I'm fully committed to keeping these tools alive. I've been using Send2UE since launch and can't live without haha.

If you would be okay with allowing me to continue displaying my ko-fi link there, I'd be happy to admin your fork! I'm struggling financially right now so I was planning to use my dedication to these tools as a means to accept donations for upkeep and fixing my private server. The SSD with my game and everything on it was fried by a brownout last month so I'm trying to afford a replacement 😭

**Comment by JoshQuake** [comment]
As for the [Latest test fails you mentioned](https://github.com/poly-hammer/BlenderTools/actions/runs/9489301811) I think I have a viable fix in #12 that I can adapt and make compliant with your fork.

**Comment by jack-yao91** [comment]
Ok great! I just added you as the maintainer and added your ko fi links. Later today I can add a slack channel to our org for the BlenderTools repo so you can have a more direct line of communication to me if you need anything 👍
